### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by stowers95120** [explosivo22/rinnaicontrolr-ha#36]
Could you add:
* the ability to set schedules
* switch on/off vacation mode

**Comment by stowers95120** [comment]
Thank you!

**Comment by stowers95120** [comment]
I have updated my integration to 1.3.5 but don't see the enable/disable_vaaction_mode services. Am I doing something wrong?

**Comment by explosivo22** [comment]
The service is `water_heater.set_away_mode`. You can also toggle it when you aer viewing the water heater entity at the bottom of adjusting temperature.

**Comment by explosivo22** [comment]
I am glad things are working for you.  

I don't believe I will be implementing schedules for the water heater in HA after reviewing everything.  I think we will leave scheduling in HA to automations and scheduling in the Rinnai app independently. I know there is the current 5 minute bug with recirculation that will only run longer with schedules, but Rinnai has told me an update is coming that should fix this.

I think for simplicity of the integration this will be the best solution unless I can be convinced otherwise.

**Comment by stowers95120** [comment]
I agree with you - I don't think you need to implement schedules.

Hopefully Rinnai will fix the 5 minute bug soon, but in any case we now have a workable system: I have a schedule that operates recirculation all the time (00:00 through 23:59) and then use your recently implemented away mode to switch on/off recirculation as needed.

**Comment by explosivo22** [comment]
Sounds good. I thought for a while on this.

I hope they do fix it sooner than later. I may ping them again to see if they have some kind of timeline.

I am glad that the away mode is working out for you at this time.
